import {
  LayoutDashboard,
  Users,
  KeyRound,
  Box,
  Ruler,
  Hash,
  ListOrdered,
  Building2,
  Wallet,
  Network,
  Truck,
  FileCode,
  Barcode,
  Cog,
  Factory,
  List,
  ClipboardCheck,
  Package,
  FileText,
  Contact,
  Inbox,
  Cpu,
  Wrench,
  Heart,
  Monitor,
  History,
  Mail,
  Shield,
  Settings,
  LogOut,
  Sun,
  Moon,
  Bell,
  Plus,
  Home,
  User,
  StickyNote,
  Zap,
  QrCode,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "bbyd-dashboard": LayoutDashboard,
  home: Home,
  employee: User,
  group: Users,
  role: KeyRound,
  product: Box,
  dimension: Ruler,
  "number-sign": Hash,
  "bullet-text": ListOrdered,
  "org-chart": Network,
  "money-bills": Wallet,
  "customer-and-supplier": Building2,
  supplier: Truck,
  "attachment-html": FileCode,
  "bar-code": Barcode,
  process: Cog,
  factory: Factory,
  list: List,
  measure: Ruler,
  survey: ClipboardCheck,
  request: Package,
  document: FileText,
  "customer-and-contacts": Contact,
  "shipping-status": Inbox,
  forklift: Package,
  machine: Cpu,
  laptop: Monitor,
  wrench: Wrench,
  approvals: Shield,
  email: Mail,
  heart: Heart,
  "sys-monitor": Monitor,
  history: History,
  log: LogOut,
  "dark-mode": Moon,
  "light-mode": Sun,
  bell: Bell,
  add: Plus,
  attachment: StickyNote,
  action: Zap,
  "qr-code": QrCode,
  grid: BarChart3,
  "table-view": List,
  "key-user-settings": Settings,
  "official-service": Cog,
  accept: BarChart3,
};

export function getNavIcon(name?: string): LucideIcon {
  if (!name) return LayoutDashboard;
  const Icon = iconMap[name] ?? LayoutDashboard;
  return Icon;
}
