import {
  LayoutDashboard,
  KeyRound,
  Box,
  Ruler,
  Hash,
  ListOrdered,
  Network,
  Wallet,
  Truck,
  FileCode,
  Barcode,
  Cog,
  Factory,
  List,
  ClipboardCheck,
  Package,
  FileText,
  Contact,
  Inbox,
  Cpu,
  Wrench,
  Heart,
  Monitor,
  History,
  Mail,
  Shield,
  User,
  StickyNote,
  Zap,
  QrCode,
  BarChart3,
  AlertTriangle,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "bbyd-dashboard": LayoutDashboard,
  role: KeyRound,
  product: Box,
  dimension: Ruler,
  "number-sign": Hash,
  "bullet-text": ListOrdered,
  "org-chart": Network,
  "money-bills": Wallet,
  "customer-and-supplier": Truck,
  "attachment-html": FileCode,
  "bar-code": Barcode,
  process: Cog,
  factory: Factory,
  list: List,
  measure: Ruler,
  survey: ClipboardCheck,
  request: Package,
  document: FileText,
  "customer-and-contacts": Contact,
  "shipping-status": Inbox,
  machine: Cpu,
  laptop: Monitor,
  wrench: Wrench,
  approvals: Shield,
  email: Mail,
  heart: Heart,
  "sys-monitor": Monitor,
  history: History,
  employee: User,
  attachment: StickyNote,
  action: Zap,
  "qr-code": QrCode,
  "create-form": FileText,
  warning: AlertTriangle,
  "chain-link": BarChart3,
};

export function getPageLayoutIcon(name?: string): LucideIcon {
  if (!name) return LayoutDashboard;
  return iconMap[name] ?? LayoutDashboard;
}
